-
  hosts: db
  user: docker
  become: yes

  tasks:
    - name: Install all the requirements
      apt:
        update_cache: yes
        name:
          - nginx
          - nginx-extras
          - python3
          - pip
          - venv
        state: present
      when: ansible_facts['os_family']='Debian'
