-
  vars_files:
    - /home/ansible/ansible_course/Ansible_Task/secrets/secrets.yaml 

- name: User Creation
  user:
    name: details_app
    shell: /bin/bash
    create_home: yes
    password: "{{ user_password }}"

- name: Add the user to Sudoers group
  copy:
    dest: "/etc/sudoers.d/details_app"
    content: "details_app ALL=(ALL) NOPASSWD:ALL"  
    mode: '0440'
