-
- block:
  - name: Deploy Venv Enviroment in Debian
    shell:
  when: ansbile_facts['os_family'] == "Debian"



- block:
    - name: Deploy Venv Enviroment in RedHat
  when: ansible_facts['os_family'] == "RedHat"
