-
  name: Main Playbook
  hosts: db
  user: docker
  become: yes
  gather_facts: yes

  tasks:
    - name: Create Details_app user
      import_tasks: playbook_install_tools.yaml
        #- name: Install Tools
        #- name: Copy Project Files

