-
  name: Main Playbook
  hosts: db
  user: docker
  become: yes
  gather_facts: yes

  tasks:
    - name: Install all the tools
      import_tasks: playbook_install_tools.yaml
    - name: Create Details_app user
      import_tasks: playbook_user_creation.yaml
        #- name: Copy Project Files

