
- block:
    - name: Install Tools on Debian based systems
      apt:
        update_cache: yes
        name:
          - nginx
          - nginx-extras
          - python3
          - python3-venv
          - pip
        state: present
  when: ansible_facts['os_family'] == 'Debian'

- block:
    - name: Install Tools on RedHat Based system
      dnf:
      name:
        - nginx
        - python3
        - python3-pip
      state: present
     
    - name: Install Venv
      pip:
        name: virtualenv
        executable: pip3
  when: ansible_facts['os_familiy'] == 'RedHat' 
