-

- name: User Creation
  user:
    name: details_app
    shell: /bin/bash
    create_home: yes
    password: $6$PTgsqJ4yCHZSKUdD$nHY/ePusFEUPh5k/oU9mR/XYkR91edgQof8s.14kTohxGFuis1VSA.fyEDvdUGfNHGlYzKzWpjf66IFHWNHGT.


- name: Add the user to Sudoers group
  copy:
    dest: "/etc/sudoers.d/details_app"
    content: "details_app ALL=(ALL) NOPASSWD:ALL"  
    mode: '0440'
