-
  hosts: db
  user: docker
  become: yes
  gather_facts: yes

  tasks:
    - name: Copy project files to /home/details_app/
      copy:
        src: "/home/ansible/ansible_course/Ansible_Task/{{ item }}"
        dest: /home/details_app/
      loop:
        - src
        - config
        - automation

    - block:
        - name: Install tools on Debian linux
          apt:
            update_cache: yes
            name:
              - nginx
              - nginx-extras
              - python3
              - pip
              - python3-venv
            state: present
      when: ansible_facts['os_family'] == 'Debian'
      
    - block:
        - name: Install tools on Rocky linux
          dnf:
            name:
              - nginx
              - python3
              - python3-pip
            state: present

        - name: Install venv
          pip:
            name: virtualenv
            executable: pip3      
      when: ansible_facts['os_family'] == 'RedHat'
